name: Flutter SDK Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Run install packages
        run: flutter pub get
      - name: Run code format
        run: dart format . --set-exit-if-changed
      - name: Run code lint
        run: flutter analyze --fatal-warnings
